# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook 'rs-application_php', github: 'rightscale-cookbooks/rs-application_php'
cookbook 'rs-haproxy', github: 'rightscale-cookbooks/rs-haproxy'
cookbook 'rs-base', github: 'rightscale-cookbooks/rs-base'
cookbook 'rsc_remote_recipe', github: 'rightscale-services-cookbooks/rsc_remote_recipe'
