AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - 'knife.rb'
Style/WhileUntilDo:
  Exclude:
    - 'test/integration/default/serverspec/server_spec.rb'
Lint/AssignmentInCondition:
  Exclude:
    - 'test/integration/default/serverspec/server_spec.rb'
